== Mengenal Kotlin (wip)

Kotlin adalah spesifikasi bahasa pemrograman serta peranti kompilator (*compiler tools*) yang dibuat oleh JetBrains (perusahaan berbasis di St. Petersburg - Rusia, pembuat IDE IntelliJ IDEA). Untuk penyebutan selanjutnya, Kotlin akan mengacu pada spesifikasi bahasa pemrograman serta *compiler* yang mengimplementasikan spesiikasi tersebut.

Kotlin termasuk dalam kategori bahasa pemrogaman *statically-typed*, yaitu mensyaratkan berbagai konstruksi bahasa pemrograman tersebut untuk mempunyai tipe yang pasti sehingga pengubahan tipe saat menjalankan program tidak bisa dilakukan. Kepastian tipe ini juga membuat hasil kompilasi lebih kecil dan lebih cepat karena tidak perlu ada mekanisme untuk pengaturan tipe dinamis.

Kotlin memerlukan JDK, bisa dikompilasi ke *byte code Java Virtual Machine* dan bisa dijalankan di JRE. Selain itu Kotlin juga bisa dikompilasi ke JavaScript. Kompilasi ke native code juga tersedia tetapi masih belum stabil dan bukan merupakan versi resmi yang didukung oleh Kotlin.

=== Aplikasi Apa yang Cocok Dikembangkan Menggunakan Kotlin?

Kotlin digunakan untuk berbagai macam aplikasi. Penggunaan utama dari Kotlin adalah sebagai peranti pengembangan untuk Android. Meskipun demikian, Kotlin juga kuat di sisi server / backend serta aplikasi-aplikasi infrastruktur (teknologi blockchain Corda dibuat menggunakan Kotlin). Kotlin tidak bisa / tidak sesuai digunakan untuk pemrograman aras rendah (low-level programming) atau pemrograman untuk Hardware.

