== Algoritma, Pemrograman, Paradigma Pemrograman, dan Python

=== Pengertian Algoritma

Istilah *Algoritma* berasal dari nama matematikawan abad 9, yaitu * Muḥammad ibn Mūsā al-Khwārizmī* (pada bahasa latin, dipanggil dengan nama *Algoritmi*). Algoritma merupakan spesifikasi langkah dalam menyelesaikan suatu masalah. 

Pada intinya, pemrograman diperlukan untuk membuat solusi terhadap suatu permasalahan tertentu. Seorang pemrograman meruapakan seseorang yang bertugas untuk membuat program. Proses pembuatan program tersebut sering disebut juga dengan *coding*. Proses *coding* tersebut pada dasarnya adalah proses untuk menganalisis masalah, mengabstraksi masalah, mewujudkan abstraksi tersebut dalam bentuk *algoritma*, mengimplementasikan algoritma tersebut dengan suatu bahasa pemrograman tertentu, menguji implementasi tersebut, serta melakukan proses *debugging* saat terjadi kesalahan. Pada banyak kasus, sering juga tidak hanya sampai disitu, tetapi juga sampai ke analisis algoritma untuk mencari algoritma yang paling optimum.

=== Pembuatan Algoritma

Untuk membangun suatu program dengan melibatkan algoritma, biasanya diperlukan langkah-langkah berikut ini:

1. Definisi masalah
2. Abstraksi masalah dalam bentuk model
3. Spesifikasikan dan rancang langkah-langkah untuk menyelesaikan model tersebut
4. Implementasikan rancangan tersebut dalam *source code*.
5. Uji kebenaran algoritma tersebut, biasanya dengan membuat test yang terdiri atas masukan serta keluaran yang dikehendaki.
6. *Debug* atau cari kesalahan jika terdapat kesalahan. Betulkan kesalahan tersebut.
7. Jika sudah berjalan, cari lagi algoritma yang paling baik - proses ini disebut *optimasi* dan bisa dilakukan dengan analisis algoritma.
8. Testing program
9. Buat dokumentasi.

=== Representasi Algoritma

Jika digambarkan, algoritma sering diwujudkan dalam bentuk alur program (*flowchart*) maupun dalam bentuk *pseudocode*. Pembuatan *flowchart* maupun *pseudocode* ini seringkali digunakan dalam dunia akademik dan relatif jarang digunakan di industri. Meskipun demikian, bisa dipastikan bahwa setiap pemrogram - tidak peduli di industri maupun dunia akademik - akan selalu menggunakan algortima.

Contoh algoritma untuk mencari nilai terbesar dari sekumpulan angka adalah sebagai berikut (diambil dari https://en.wikipedia.org/wiki/Algorithm):

[source,ruby]
----
Algorithm LargestNumber
  Input: A list of numbers L.
  Output: The largest number in the list L.
  if L.size = 0 return null
  largest ← L[0]
  for each item in L, do
    if item > largest, then
      largest ← item
  return largest
----

=== Algoritma dan Paradigma Pemrograman

Paradigma pemrograman merupakan cara pandang dari pemrogram untuk mengimplementasikan algoritma serta menyelesaikan suatu masalah tertentu dalam pemrograman. Perbedaan antara berbagai paradigma ini terutama dalam hal implementasi algoritma serta komponen dan unit terkecil untuk *reusable code*. Pada umumnya, saat ini ada beberapa paradigma pemrograman yang banyak diimplementasikan dalam bahasa pemrograman:

1. **Prosedural**: implementasi algoritma dalam bentuk langkah-langkah prosedural dan unit terkecil diabstraksi dalam bentuk *procedure* (tidak menghasilkan nilai kembalian) maupun *function* (menghasilkan nilai kembalian). 
2. **Fungsional**: implementasi algoritma dalam bentuk langkah-langkah dengan ketetapan prinsip-prinsip matematika dan unit terkecil diimplemtasikan dalam bentuk *function*.
3. **Object-oriented**: implementasi algoritma dalam bentuk langkah-langkah dengan menggnakan pola pikir natural dengan prinsip-prinsip obyek dan unit terkecil diimplementasikan dalam bentuk kelas (*class*) serta pembuatan *instance* atau obyek yang saling bekerjasama dan berinteraksi.

Python mendukung ketiga pola pikir dan paradigman pemrograman tersebut. Secara umum, paradigma
pertama (*prosedural*) relatif lebih mudah dipahami daripada dua paradigma lainnya. Dalam proses
pembelajaran, biasanya paradigma *prosedural* ini yang lebih dulu dipelajari. 

=== Python dan Implementasi Algoritma

Python merupakan bahasa pemrograman yang mempunyai sintaksis atau tata bahasa yang menyerupai *pseudocode* sehingga relatif mudah mudah untuk dipelajari (khususnya jika bahasa Inggris tidak menjadi masalah). Secara umum, implementasi Python dari algoritma bisa diwujudkan dalam proses berikut ini:

1. Definisi masalah
2. Rancang algoritma
3. Gunakan sintaks Python untuk mengimplementasikan langkah per langkah dari algoritma.

Contoh dari proses tersebut adalah sebagai berikut:

1. Definisi masalah
+
[source,shell]
----
Menentukan nilai nilai terbesar antara kedua angka
----
+
2. Rancang algoritma
+
[source,shell]
----
0. mulai
1. meminta masukan angka pertama
2. meminta masukan angka kedua
3. pemeriksaan dan penentuan hasil:

Jika angka pertama lebih besar daripada angka kedua:
  cetak angka pertama sebagai angka terbesar
Selain itu, jika angka pertama lebih kecil daripada angka kedua
  cetak angka kedua sebagai angka terbesar
Selain itu, jika angka pertama sama dengan angka kedua
  cetak pemberitahuan bahwa tidak ada angka terbesar karena sama
Selain itu,
  cetak pemberitahuan bahwa ada kesalahan masukan

4. selesai
----
+
3. Implementasikan dalam Python

Setelah memodelkan penyelesaian dalam bentuk algoritmis berupa langkah-langkah, cari perintah-perintah Python yang bisa digunakan untuk menyelesaikan langkah-langkah tersebut:

1. meminta masukan: *input()*
2. memeriksa dan menentukan hasil: *if ... elif ... else*
3. mencetak: *print*

Cara mengetahui perintah-perintah tersebut biasanya dengan melihat pada manual dokumentasi dari
bahasa pemrograman. Manual bahasa pemrograman biasanya minimal terdiri atas 2 bagian:

1. Dokuemntasi sintaksis: konstruksi bahasa pemrograman (variabel, function, class,  *statement* pengendali, dan lain-lain).
2. Dokumentasi pustaka / perintah standar: perintah-perintah siap pakai (menampilkan tulisan / print, akses ke sistem operasi, pemrosesan file, dan lain-lain).

Setelah itu, implementasikan algoritma tersebut:

[source,python]
.src/01-03/angka-max/01-max.py
----
include::../{sourcedir}/01-03/angka-max/01-max.py[]
----
<1> Perintah *input* digunakan untuk meminta masukan melalui keyboard
<2> *if* digunakan untuk memeriksa ekpresi dan melakukan sesuatu berdasarkan hasil pemeriksaan. *(angka1 > angka2)* adalah bentuk ekspresi.
<3> *print* pada bagian ini adalah perintah yang akan dikerjakan jika hasil pemeriksaan ekspresi menghasilkan nilai benar (_True_).

Untuk menjalankan:

[source,shell]
----
include::../{sourcedir}/01-03/angka-max/01-hasil.txt[]
----

Setelah algoritma diimplementasikan dan kemudian kode sumber bisa dijalankan, maka seringkali muncul masalah. Sebagai contoh, kode sumber di atas sudah bisa dijalankan dengan baik, tetapi jika diisikan bukan angka, maka kode sumber tetap berjalan dan memberikan hasil. Hal ini tentu saja tidak diinginkan. Apa yang harus dilakukan? secara sederhana, pemrogram kemudian berpikir bahwa *berarti harus ada mekanisme untuk memeriksa apakah angka yang dimasukkan tersebut angka atau bukan*. Setelah mempunyai pikiran seperti ini, pemrogram kemudian mencari cara (di manual, di Internet, bertanya ke rekan-rekan, dan lain-lain) untuk memeriksa apakah input yang dimasukkan tersebut angka atau bukan. Dari proses pencarian, diperoleh suatu fungsi untuk memeriksa apakah angka atau bukan, yaitu *isnumeric*. Kode sumber kemudian kita ubah untuk keperluan tersebut.

[source,python]
.src/01-03/angka-max/02-max-check-numeric.py
----
include::../{sourcedir}/01-03/angka-max/02-max-check-numeric.py[]
----
<1> Memeriksa apakah isi angka1 dan angka2 numerik atau bukan dengan *isnumeric()*

Untuk menjalankan:

[source,shell]
----
include::../{sourcedir}/01-03/angka-max/02-hasil.txt[]
----
