== Struktur Data di Python

Struktur data merupakan pengorganisasian, pengelolaan, serta penyimpanan data untuk akses data yang efisien. Python mempunyai beberapa model data. Pembahasan mengenai struktur data merupakan pembahasan lebih lanjut lagi setelah tipe data dasar. Pada tipe data dasar, kita sudah mengetahui bahwa ada beberapa tipe data bawaan (sering disebut dengan *primitive*) dan paling mendasar. Tipe data dasar tersebut biasanya memang hanya digunakan untuk keperluan yang sederhana dan sifatnya individual. 

Tipe data primitif tersebut kemudian bisa digunakan untuk mengkonstruksi tipe data yang lebih kompleks. Secara umum, tipe data yang dibentuk dari konstruksi tipe data primitif tersebut dikenal dengan istilah _struktur data_ atau tipe data _agregat_. Istilah lain yang juga cukup sering digunakan adalah _composite data type_ atau _compound data type_. Saat pemrograman melakukan proses untuk mengkonstruksi _composite data type_, maka dikatakan bahwa pemrogram melakukan _composition_ / komposisi.

=== List

List digunakan untuk menyimpan data (biasanya) dari tipe yang sama (meski tidak selalu harus sama) dalam suatu rangkaian data yang dipisahkan oleh koma dalam kurung kotak.

[source,python]
.src/02-05/01_list.py
----
include::../{sourcedir}/02-05/01_list.py[]
----

Hasilnya adalah sebagai berikut:

[source,shell]
----
include::../{sourcedir}/02-05/01_list.txt[]
----

Python menyediakan banyak fungsi untuk memanipulasi list, silahkan melihat selengkapnya dengan perintah help(list) dari prompt Python. Berikut adalah contoh kode sumber yang berisi berbagai fungsi / _method_ untuk memanipulasi list:

[source,python]
.src/02-05/02_list.py
----
include::../{sourcedir}/02-05/02_list.py[]
----

Hasilnya adalah sebagai berikut:

[source,shell]
----
include::../{sourcedir}/02-05/02_list.txt[]
----

=== Tuple
	
Tuple mirip dengan list, tetapi beda kurung dan bersifat immutable (tidak bisa diubah).

[source,python]
.src/02-05/03_tuple.py
----
include::../{sourcedir}/02-05/03_tuple.py[]
----

Hasilnya adalah sebagai berikut:

[source,shell]
----
include::../{sourcedir}/02-05/03_tuple.txt[]
----

Untuk mengetahui fungsi serta _method_ untuk tuple, lihat juga *help(tuple)* dari REPL.

=== Sets

Sets merupakan struktur data untuk koleksi yang tidak terurut tetapi tidak membolehkan lebih dari satu nilai yang sama dalam setiap koleksi tersebut.

[source,python]
.src/02-05/04_set.py
----
include::../{sourcedir}/02-05/04_set.py[]
----

Hasilnya adalah sebagai berikut:

[source,shell]
----
include::../{sourcedir}/02-05/04_set.txt[]
----

Lihat juga *help(set)* dari REPL.

=== Dictionary

Struktur data ini mengorganisasikan data dalam bentuk seperti kamus: ada key dan value untuk key tersebut. 

[source,python]
.src/02-05/05_dict.py
----
include::../{sourcedir}/02-05/05_dict.py[]
----

Hasilnya adalah sebagai berikut:

[source,shell]
----
include::../{sourcedir}/02-05/05_dict.txt[]
----

Lihat juga *help(dict)* dari REPL
