== Mulai Menggunakan Python

Python bisa digunakan dengan 2 cara:

1. REPL (*Read-Eval-Print-Loop*)
2. *Coding* - membuat kode sumber dalam bahasa pemrograman Python dan kemudian di-eksekusi / dijalankan menggunakan *interpreter* Python.

=== REPL
	
REPL digunakan untuk keperluan mencoba potongan kode sumber. Untuk keluar dari REPL maupun dari *help>*, gunakan *Ctrl-D*

[source,shell]
----
include::../{sourcedir}/screen/02-01/01-repl.txt[]
----

Contoh penggunaan:

[source,python]
----
>>> for i in range(5):
...	print(i)
...
0
1
2
3
4
5
>>> a = 20
>>> a
20
>>>
----

Pada REPL, a akan menghasilkan angka 20 (nilai dari a) karena sifat P di dalam REPL yang akan menampilkan (Print) hasil evaluasi. Di dalam script, harus eksplisit menggunakan perintah print jika ingin menampilkan seseuatu. Setelah selesai dan ingin keluar dari REPL, tekan Ctrl-D.

=== Coding

Jika software yang akan dibuat mulai besar dan serius, maka REPL tidak cocok digunakan lagi. Untuk keperluan ini, tulis source code dalam bahasa pemrograman Python, kemudian jalankan dengan menggunakan interpreter Python. Penulisan source code biasanya memerlukan suatu software khusus, sebagai contoh, programmer Python bisa menggunakan vim, Emacs, Visual Studio Code, dan lain-lain. Untuk keperluan ini, ada 3 cara:

1. Cara 1
+
[source,shell]
----
# hello.py 
print('Halo')
$ python hello.py 
Halo
$ 
----
+
2. Cara 2
+
[source,shell]
----
# hello2.py 
#!/usr/bin/env python

print('Halo')
$ chmod +x hello2.py
$ ./hello2.py 
Halo
$ 
----
+
3. Cara 3
+
[source,shell]
----
# hello3.py 
#!/opt/software/python-dev-tools/miniconda3/bin/python

print('Halo')
$ chmod +x hello2.py
$ ./hello3.py 
Halo
$ 
----

