== Perintah Dasar Python

Suatu bahasa pemrograman mempunyai perintah serta fasilitas _builtin_ untuk merangkai instruksi supaya bisa digunakan untuk memecahkan masalah pemrograman. Bisa dikatakan bahwa kode sumber Python yang dibuat nantinya akan terdiri atas:

1.  Data
2.  Fasilitas pustaka _builtin_
3.  Perintah-perintah Python
4.  Fasilitas pustaka pihak ketiga (jika diperlukan).

Data telah dibahas pada bab tentang "Dasar-dasar Python", khususnya tentang tipe data dasar. Tipe data yang lebih kompleks akan dibahas pada bab mendatang. Fasilitas pustaka _builtin_ maupun pihak ketiga juga akan dibahas pada bab berikutnya. Untuk pembuatan program sederhana / belum kompleks, diperlukan pemahaman tentan tipe data dasar dan perintah-perintah Python (serta beberapa pustaka _builtin_ dasar). Bagian ini akan membahas perinta-perintah Python.


Perintah-perintah Python - sering disebut juga dengan _statement_ - terdiri atas perintah *sederhana* (_simple statement_) dan perintah *gabungan* (_compound statement_). 

=== _Simple Statement_

Perintah sederhana / _simple statement_ adalah perintah yang terdiri atas satu baris saja ataupun satu baris yang terdiri atas beberapa rangkaian perintiah kecil. Perintah untuk mengisi variabel adalah salah satu contoh dari perintah sederhana. Beberapa perintah lain:

1.  Mengisi variabel
2.  Ekspresi
3.  Perintah _assert_
4.  Perintah _pass_
5.  Perintah _del_
6.  Perintah _return_
7.  Perintah _yield_
8.  Perintah _raise_
9.  Perintah _break_
10. Perintah _continue_
11. Perintah _import_
12. Perintah _global_
13. Perintah _nonlocal_

=== _Compound Statement_

Perintah gabungan / _compound statement_ adalah perintah yang berisi sekelompok perintah lainnya. 

==== if 

Python menyediakan if … elif … else serta variasinya untuk keperluan jika terjadi kondisi tertentu dalam aliran program dan diteruskan dengan suatu ekspresi tertentu. Bentuk dari pernyataan if ini adalah sebagai berikut:

[,python]
----
nilai = int(input("Masukkan nilai siswa = "))
 
if nilai > 60:
    print("Lulus")
else:
    print("Tidak lulus")
 
if nilai <= 10:
    print("Anda harus mengulang semester depan")
 
ipsemester = float(input("Masukkan nilai IP semester = "))
 
if ipsemester > 3:
    print("Anda bisa mengambil 24 SKS")
elif ipsemester >= 2.75:
    print("Anda bisa mengambil 21 SKS")
elif ipsemester >= 2:
    print("Anda bisa mengambil 18 SKS")
else:
    print("Anda hanya bisa mengambil 12 SKS")
----

==== while

Pernyataan while digunakan untuk menjalankan perintah ataupun ekspresi di dalam blok while selama kondisi masih bernilai True.

[,python]
----
nilai = 1
 
# akan ditampilkan angka 1 - 9 
# setelah itu berhenti
while nilai < 10:
    print(nilai)
    nilai += 1
 
while nilai <= 20:
    print(nilai)
    nilai += 1
else:
    print("nilai sudah mencapai 20 ...")
 
input("Tekan sembarang tombol untuk meneruskan ... ")
 
# akan ditampilkan angka 21
# dan seterusnya tidak akan berhenti
# kecuali ditekan Ctrl-C
while True:
    print(nilai)
    nilai += 1
----

==== for

Pernyataan for digunakan untuk melakukan iterasi sepanjang list / daftar maupun string.

[,python]
----
daftar = ["first", "2nd", 3]
 
for a in daftar:
    print(a)
 
for a in range(20):
    print(a) # 0 - 19
 
for a in range(1, 5):
    print(a) # 1 -4
 
for w in 'ABCDEFG':
    print(w)
 
# range(start, stop, step)
for a in range(1, 5, 2):
    print(a) # 1, 3
else:
    print("bukan selisih 2")
 
for a in range(20):
    if a > 0 and a % 2 == 0:
        print(a, " habis dibagi dua")
    else:
        print(a, " ganjil")
----

