== Menangani Error dan Exception

Saat membuat program, seorang pemrogram tidak akan terlepas dari kondisi-kondisi yang terkait dengan program yang dia buat, khususnya kemungkinan terjadinya kesalahan. Python mempunyai berbagai macam konstruksi untuk mendeteksi error (yang paling sederhana, misalnya SyntaxError) jika terdapat hal-hal yang bisa diketahui kesalahannya sejak awal. Meski demikian, sering kali jika tidak ada error juga tidak menjamin bahwa saat dijalankan tidak akan terjadi hal-hal yang di luar dugaan. Tugas pemrogram adalah mengantisipasi berbagai macam kondisi tersebut.

Saat terjadi error, pemrogram melihat pada error yang terjadi, setelah itu memperbaiki berdasarkan error yang muncul. Seringkali hal ini juga melibatkan pembacaan manual / dokumentasi dan penggunaan sumber daya di Internet (StackOverflow dan lain-lain) untuk melihat kemungkinan solusi. Berikut ini adalah contoh perintah-perintah yang menimbulkan error:

[source,python]
----
include::../{sourcedir}/02-08/01-error.txt[]
----
<1> Kesalahan yang muncul karena file yang akan dibuka tidak ada.
<2> Kesalahan yang muncul karena mode pembukaan file yang salah.
<3> Kesalahan yang muncul karena kesalahan sintaksis.

Setiap terjadi error, Python akan memunculkan *exception* atau suatu kondisi “pengecualian”. Pemrogram biasanya harus waspada terhadap berbagai kemungkinan *error* serta *exception* yang terjadi untuk diantisipasi. Untuk mengantisipasi *exception*, gunakan `try … except … else … finally`.

[source,python]
----
include::../{sourcedir}/02-08/02-except.py[]
----

Hasil dari kode sumber tersebut jika ada kesalahan input:

[source,shell]
----
include::../{sourcedir}/02-08/02-except-error.txt[]
----

Hasil dari kode sumber tersebut jika tidak ada kesalahan input:

[source,shell]
----
include::../{sourcedir}/02-08/02-except-no-error.txt[]
----

