== Fungsi / _Function_

=== Apakah Fungsi Itu?

Fungsi (_function_) merupakan blok / unit dari program yang digunakan untuk mengerjakan suatu pekerjaan tertentu dan mengembalikan hasilnya ke pemanggil. Hasil yang dikembalikan bisa merupakan data maupun hasil eksekusi suatu _statement_ untuk mengerjakan _task_ tertentu. Fungsi dimaksudkan utk membuat _reusable code_. Seringkali dalam memprogram, seorang pemrogram mengerjakan hal-hal yang kadang sama dan diulang berkali-kali. Untuk membuat supaya tidak perlu mengerjakan tugas yang berulang-ulang tersebut, kode program dimasukkan dalam fungsi. saat diperlukan, fungsi tersebut dipanggil.

=== Membuat Fungsi

Rerangka fungsi di Python adalah sebagai berikut:

[source,python] 
----
def nama(arg1, arg2, ... , argN):
	... 
	Isi fungsi
	... 
 
# memanggil fungsi:
 
retvalnama = nama(arg1, arg2, ... , argN)
----

Contoh:

[source,python]
.src/02-04/01_function.py
----
include::../{sourcedir}/02-04/01_function.py[]
----
<1> Mendefinisikan nama fungsi (*jumlah*) dan argumen dari fungsi.
<2> Awal dari *statement* yang akan dikerjakan jika fungsi tersebut dipanggil. Sering juga disebut dengan istilah "body of function". 
<3> Setelah diproses, nilai akan dikembalikan ke pemanggil menggunakan _return_.
<4> Definisi variabel yang akan diproses oleh kode sumber.
<5> Pemanggilan fungsi pertama.
<6> Pemanggilan fungsi kedua. 
<7> Pemanggilan fungsi ketiga, Dari tiga pemanggilan ini, kita bisa melihat _reusable code_, sekali didefinisikan, setelah itu tidak perlu menulis ulang lagi, tinggal dipanggil namanya beserta dengan argumen yang diperlukan.

Hasilnya adalah sebagai berikut:

[source,shell]
----
include::../{sourcedir}/02-04/01_function.txt[]
----

=== Fungsi Dengan Argumen Default

Suatu fungsi bisa mempunyai argumen default dengan cara menetapkan nilainya secara langsung pada definisi fungsi. Jika saat pemanggilan fungsi tersebut tidak menyertakan argumen, maka argumen default tersebut yang digunakan.

[source,python]
.src/02-04/02_function_default.py
----
include::../{sourcedir}/02-04/02_function_default.py[]
----

Hasilnya adalah sebagai berikut:

[source,shell]
----
include::../{sourcedir}/02-04/02_function_default.txt[]
----

=== Fungsi Dengan Argumen Tidak Pasti
  
Jika jumlah argumen tidak pasti, pemrogram bisa menggunakan *args (untuk argumen tanpa _key_) dan **kwargs (untuk argumen dengan _key_ dan _value_).

[source,python]
.src/02-04/03_function_args_kwrgs.py
----
include::../{sourcedir}/02-04/03_function_args_kwargs.py[]
----

Hasilnya adalah sebagai berikut:

[source,shell]
----
include::../{sourcedir}/02-04/03_function_args_kwargs.txt[]
----

Dengan adanya jumlah argumen tidak pasti serta penggunaan *args dan **kwargs, maka urutan definisi argumen dalam suatu deklarasi fungsi menjadi penting. Urutan deklarasi argumen suatu fungsi yang benar adalah sebagai berikut:

1.  Argumen standar
2.  *args
3.  **kwargs

=== Ekspresi / Operator / Fungsi Lambda

Fungsi lambda merupakan fungsi kecil dan tanpa nama. Penggunaannya mirip dengan fungsi biasa, tetapi meski bisa menggunakan banyak argumen, fungsi lambda hanya terdiri atas 1 ekspresi yang dieksekusi dan langsung dikembalikan nilainya ke pemanggilnya. Penggunaan dari fungsi lambda ini antara lain untuk:

* _Higher order function_ (lihat materi Functional Programming) atau fungsi yang mempunyai argumen berupa fungsi, 
* Digunakan bersama struktur data di Python (misalnya untuk map dan filter di list).
* Digunakan untuk membuat fungsi secara cepat dan dalam waktu pendek saja.

[source,python]
.src/02-04/04_lambda.py
----
include::../{sourcedir}/02-04/04_lambda.py[]
----

Hasilnya adalah sebagai berikut:

[source,shell]
----
include::../{sourcedir}/02-04/04_lambda.txt[]
----

=== +__main__+ 

Saat script Python dipanggil / dieksekusi / dijalankan, variabel +__name__+ akan berisi nama modul. Jika file tersebut merupakan program utama (bukan modul), maka +__name__+ akan berisi +__main__+. Pada Python versi 2, hal ini bisa dideteksi dengan menggunakan baris:

[,python]
----
if __name__ == "__main__":
----

Pada Python 3, langung memanggil *main()*.

[source,python]
.src/02-04/05_main.py
----
include::../{sourcedir}/02-04/05_main.py[]
----

Hasilnya adalah sebagai berikut:

[source,shell]
----
include::../{sourcedir}/02-04/05_main.txt[]
----
