== Struktur Data di Python

Struktur data merupakan pengorganisasian, pengelolaan, serta penyimpanan data untuk akses data yang efisien. Python mempunyai beberapa model data. Pembahasan mengenai struktur data merupakan pembahasan lebih lanjut lagi setelah tipe data dasar. Pada tipe data dasar, kita sudah mengetahui bahwa ada beberapa tipe data bawaan (sering disebut dengan *primitive*) dan paling mendasar. Tipe data dasar tersebut biasanya memang hanya digunakan untuk keperluan yang sederhana dan sifatnya individual. 

Tipe data primitif tersebut kemudian bisa digunakan untuk mengkonstruksi tipe data yang lebih kompleks. Secara umum, tipe data yang dibentuk dari konstruksi tipe data primitif tersebut dikenal dengan istilah _struktur data_ atau tipe data _agregat_. Istilah lain yang juga cukup sering digunakan adalah _composite data type_ atau _compound data type_. Saat pemrograman melakukan proses untuk mengkonstruksi _composite data type_, maka dikatakan bahwa pemrogram melakukan _composition_ / komposisi.

=== List

List digunakan untuk menyimpan data (biasanya) dari tipe yang sama (meski tidak selalu harus sama) dalam suatu rangkaian data yang dipisahkan oleh koma dalam kurung kotak.

[source,python]
.src/02-05/01_list_01.py
----
include::../{sourcedir}/02-05/01_list.py[]
----

Hasilnya adalah sebagai berikut:

[source,shell]
----
include::../{sourcedir}/02-05/01_list.txt[]
----

Python menyediakan banyak fungsi untuk memanipulasi list, silahkan melihat selengkapnya dengan perintah help(list) dari prompt Python

=== Tuple
	
Tuple mirip dengan list, tetapi beda kurung dan bersifat immutable (tidak bisa diubah).

[,python]
----
# tuple.py
 
the_data = 234, 'data 1', 'data 2', 343
print(the_data)
# hasil: (234, 'data 1', 'data 2', 343)
 
print(the_data[2])
# hasil: data2
 
# the_data[2] = 'change this'
# error: TypeError: 'tuple' object does not support item assignment
 
data2 = 'data x', 'data y', (123, 321)
print(data2)
# hasil: ('data x', 'data y', (123, 321))
print(data2[2][1])
# hasil: 321
for a in data2:
    print(a)
# hasil:
#   data x
#   data y
#   (123, 321)
 
# membuat tuple yang hanya berisi 1:
data3 = 435,
print(data3)
# hasil: (435,)
----

Lihat juga help(tuple).

=== Sets

Sets merupakan struktur data untuk koleksi yang tidak terurut tetapi tidak membolehkan lebih dari satu nilai yang sama dalam setiap koleksi tersebut.

[,python]
----
# set.py
 
proglang = {'Rust', 'Python', 'Go', 'Rust'}
print(proglang)
tambahan = ('Ruby', 'Lua')
proglang.add(tambahan)
print(proglang)
print('Rust' in proglang)
 
huruf = set('Wabi Teknologi')
print(huruf)
 
huruf2 = set()
print(huruf2)
huruf2.add('Wabi Teknologi')
print(huruf2)
 
kata1 = set('indonesia')
kata2 = set('merdeka')
print(kata1)
print(kata2)
 
# ada di kata1, tidak ada di kata2
print(kata1 - kata2)
 
# ada di kata1 atau di kata2 atau di keduanya
print(kata1 | kata2)
 
# ada di kata1 dan kata2
print(kata1 & kata2)
 
# ada di kata1 atau di kata2 tapi tidak di keduanya
print(kata1 ^ kata2)
---- 

Lihat juga help(set).

=== Dictionary

Struktur data ini mengorganisasikan data dalam bentuk seperti kamus: ada key dan value untuk key tersebut. 

[,python]
----
# dict.py
 
rumah = {'H-304': 'Bambang Purnomosidi', 'H-303': 'Anton'}
print(rumah)
print(rumah.items())
print(rumah['H-304'])
for k, v in rumah.items():
    print(f'Rumah nomor {k} adalah tempat tinggal keluarga {v}')
 
print('H-304' in rumah)
print('H-305' in rumah)
print('H-304' not in rumah)
print(sorted(rumah))
----

Lihat juga help(dict)
