== Modul dan Conda

=== Modul Standar

Python menyediakan berbagai macam fungsi dan modul standar yang bisa dipakai langsung tanpa perlu menggunakan pustaka pihak ketiga. Modul standar selengkapnya bisa dilihat di https://docs.python.org/3/library/index.html. Istilah lain untuk modul standar ini adalah *pustaka standar*, *standard library*, *builtin functions*, dan *fungsi bawaan Python*. Saat melakukan instalasi interpreter Python, modul standar ini sudah bisa langsung digunakan dengan setelah sebelumnya mendekralasikan penggunakan modul tersebut menggunakan perintah *import*.

[source,python]
.src/02-06/01-modul-standar.py
----
include::../{sourcedir}/02-06/01-modul-standar.py[]
----

Jika dijalankan dari command line / shell:

[source,shell]
----
include::../{sourcedir}/02-06/01-modul-standar.txt[]
----

=== Modul yang Didefinisikan Pemakai (User Defined Module)
	
Kumpulan fungsi (dan nantinya class) yang sudah dibuat bisa disimpan dalam suatu file dan digunakan sebagai modul. Modul sering juga disebut sebagai paket (package). Modul ini berguna untuk reusable code. 
[source,python]
.src/02-06/modul02.py
----
include::../{sourcedir}/02-06/modul02.py[]
----

Jika dipanggil dari command line / shell:

[source,shell]
----
include::../{sourcedir}/02-06/modul02.txt[]
----

Jika di-import:

[source,shell]
----
include::../{sourcedir}/02-06/modul02-import.txt[]
----

Saat menemui perintah *import modul02*, python akan mencari isi dari modul standar. Jika tidak ada, maka akan dicari modul02.py pada:

* Direktori aktif saat itu
* Isi dari $PYTHONPATH
* Isi dari sys.path

[source,shell]
----
include::../{sourcedir}/02-06/searchmodulepath.txt[]
----

=== pip

Python menyediakan perintah untuk mengelola pustaka pihak ketiga jika pemrogram ingin menggunakan berbagai pustaka tersebut untuk keperluan tugas pemrograman yang diberikan ke pemrogram. Secara default, perintah yang digunakan adalah pip.

[source,shell]
----
include::../{sourcedir}/02-06/piplist.txt[]
----

Untuk menginstall paket, gunakan:

[source,shell]
----
include::../{sourcedir}/02-06/pipinstall.txt[]
----

pip masih mempunyai banyak opsi, silahkan melihat menggunakan perintah pip --help.

=== Conda

Conda merupakan pengelola paket dan lingkungan Python yang dibuat oleh Anaconda, Inc. Hampir mirip dengan pip, hanya saja paket yang ada merupakan paket yang sudah diaudit dan dikelola dengan baik oleh Anaconda, Inc. Untuk mengelola paket, berikut adalah beberapa perintah dasar dari conda:

[source,shell]
----
include::../{sourcedir}/02-06/conda-pkg.txt[]
----
<1> daftar paket yang sudah terinstall
<2> install paket x
<3> uninstall paket x
<4> update paket x
<5> update semua paket

Selain mengelola paket, conda juga bisa digunakan untuk mengelola lingkungan karena seringkali pemrogram memerlukan python versi tertentu yang berbeda dengan yang telah diinstall (baik di level sistem operasi maupun di conda/anaconda). Berikut ini adalah beberapa perintah yang bisa digunakan untuk mengelola environment:

[source,shell]
----
include::../{sourcedir}/02-06/conda-env.txt[]
----
<1> membuat env dengan nama py311-utdi
<2> melihat env apa saja yang ada
<3> mengaktifkan environment
<4> membuat environment pada direktori tertentu, dengan versi Python tertentu
