== Instalasi Kotlin (wip)

=== Persyaratan Sistem

Kotlin berjalan di atas platform Java (JDK harus tersedia), dengan demikian, semua sistem operasi yang mendukung Java bisa digunakan. Jika mengkompilasi dari source code, maka JDK6, JDK7, JDK8, JDK9 harus tersedia (lihat repo Kotlin untuk cara kompilasi: https://github.com/JetBrains/kotlin). Materi di crash course ini menggunakan *command line compiler* yang bisa diperoleh di https://github.com/JetBrains/kotlin/releases/latest. Keluaran dari hasil kompilasi bisa ditargetkan untuk JDK6 maupun JDK8.

=== Instalasi Prasyarat (Java)

Untuk mulai menggunakan Kotlin, pastikan Java telah terinstall dengan baik (harus Java Development Kit, Java Runtime Environment saja tidak cukup. Ketikkan berikut ini untuk memeriksa:

[,shell]
----
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
$ javac -version
javac 1.8.0_181
$
----

=== Instalasi Kotlin

Untuk instalasi Kotlin, hanya perlu menggunakan mengekstrak file yang diperoleh dari repo Kotlin dan kemudian mengatur variabel lingkungan (*environemnt variable*). Misal ekstraksi dilakukan di direktori berikut:

[,shell]
----
» pwd
/opt/software/kotlin-dev-tools/kotlin-compiler-1.2.70
bpdp at archerl in /o/s/k/kotlin-compiler-1.2.70
» ls -la
total 24
drwxr-xr-x 5 bpdp bpdp 4096 Sep 14 16:13 ./
drwxr-xr-x 5 bpdp bpdp 4096 Sep 15 20:03 ../
drwxr-xr-x 3 bpdp bpdp 4096 Sep 14 16:13 bin/
-rw-r--r-- 1 bpdp bpdp   17 Sep 10 17:35 build.txt
drwxr-xr-x 2 bpdp bpdp 4096 Sep 14 16:13 lib/
drwxr-xr-x 3 bpdp bpdp 4096 Sep 14 16:13 license/
bpdp at archerl in /o/s/k/kotlin-compiler-1.2.70
»
----

Variabel lingkungan yang diatur adalah sebagai berikut:

* Jika menggunakan shell Fish:

```bash
set -x PATH $PATH /opt/software/kotlin-dev-tools/kotlinc/bin
```

* Jika menggunakan shell Bash:

[,shell]
----
export PATH $PATH:/opt/software/kotlin-dev-tools/kotlinc/bin
----

Untuk memeriksa apakah Kotlin telah terinstall:

[,shell]
----
» kotlinc -version
info: kotlinc-jvm 1.2.70 (JRE 1.8.0_144-jdk_2017_08_24_20_46-b00)
» 
----

Kotlin menyediakan fasiltas REPL (*Read-Eval-Print-Loop*) untuk mencoba source code pendek:

[,shell]
----
» kotlinc-jvm
Welcome to Kotlin version 1.2.70 (JRE 1.8.0_144-jdk_2017_08_24_20_46-b00)
Type :help for help, :quit for quit
>>> 42*10-23/4
415
>>> 42*10-23.00/4
414.25
>>> println("Selamat belajar Kotlin")
Selamat belajar Kotlin
>>> 
»
----
